name: Bump Version and Publish to NPM

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: npm ci
      - run: npm run lint

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Set up global git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Bump Version"

      - name: Share PUSH_BRANCH between all steps in job
        run: echo "::set-env name=PUSH_BRANCH::`echo "$GITHUB_REF" | awk -F / '{ print $3 }'`"

      - name: Checkout to PUSH_BRANCH
        run: git checkout $PUSH_BRANCH

      - name: Set up .netrc file with GitHub credentials
        run: |
          cat <<- EOF > $HOME/.netrc
          machine github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_IN19FARKT }}

      - name: Bump version
        run: HUSKY_SKIP_HOOKS=1 npx standard-version

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Push change log and version tag
        run: git push --follow-tags origin $PUSH_BRANCH
